services:
  front:
    build: ./client/
    ports: 
      - 80:80
    restart: always
    depends_on:
      - api
    networks:
      - main

  api:
    build: ./server/
    restart: always
    environment:
      - PG_HOST=db
    networks:
      - main

  db:
    image: postgres:16.4
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=MtgTrader
    networks:
      - main
networks:
  main:
    driver: bridge