services:
  front:
    build: ./client/
    ports: 
      - 80:80
    restart: always
    depends_on:
      - api
    networks:
      - main

  api:
    build: ./server/
    restart: always
    networks:
      - main
networks:
  main:
    driver: bridge