services:
  - type: web
    plan: free
    runtime: docker
    name: api
    dockerfilePath: ./server/Dockerfile.render
    dockerContext: ./server
    envVars:
      - key: PG_HOST
        fromDatabase:
          name: mtgtrader-db
          property: host
      - key: PG_DATABASE
        fromDatabase:
          name: mtgtrader-db
          property: database
      - key: PG_USER
        fromDatabase:
          name: mtgtrader-db
          property: user
      - key: PG_PORT
        fromDatabase:
          name: mtgtrader-db
          property: port
      - key: PG_PASSWORD
        fromDatabase:
          name: mtgtrader-db
          property: password
      - key: PORT
        value: 10000
    autoDeploy: true

  - type: web
    plan: free
    runtime: docker
    name: client
    dockerfilePath: ./client/Dockerfile.render
    dockerContext: ./client
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80

databases:
  - name: mtgtrader-db
    plan: free
