services:
  - type: web
    plan: free
    name: front
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    autoDeploy: true

  - type: web
    plan: free
    name: api
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: PG_HOST
        value: mtgtrader-db
    autoDeploy: true

databases:
  - name: mtgtrader-db
    plan: free
    databaseName: mtgtrader-db
    user: mtgtrader-user
