services:
  web:
    type: web
    plan: free
    dockerfilePath: ./client/Dockerfile 
    dockerContext: ./client
    autoDeploy: true

  api:
    type: web
    plan: free
    dockerfilePath: ./server/Dockerfile 
    dockerContext: ./server
    envVars:
      - key: PG_HOST
        value: mtgtrader-db
    autoDeploy: true

databases:
  - name: mtgtrader-db
    plan: free
    databaseName: mtgtrader-db
    user: mtgtrader-user