services:
  - type: web
    plan: free
    runtime: docker
    name: api
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: PG_HOST
        value: MtgTrader
      - key: PG_HOST
        value: MtgTrader
      - key: PG_HOST
        value: MtgTrader
      - key: PORT
        value: 7175
    autoDeploy: true

  - type: web
    plan: free
    runtime: docker
    name: front
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    autoDeploy: true
    envVars:
      - key: PORT
        value: 443

databases:
  - name: mtgtrader-db
    plan: free
