@MtgTrader.WebApi_HostAddress = http://localhost:5161

GET {{MtgTrader.WebApi_HostAddress}}/api/
Accept: application/json

POST {{MtgTrader.WebApi_HostAddress}}/api/auth/
Accept: application/json

GET {{MtgTrader.WebApi_HostAddress}}/api/user/
Accept: application/json

POST {{MtgTrader.WebApi_HostAddress}}/api/user/
Accept: application/json

GET {{MtgTrader.WebApi_HostAddress}}/api/wantlist/
Accept: application/json

POST {{MtgTrader.WebApi_HostAddress}}/api/wantlist/
Accept: application/json

PUT {{MtgTrader.WebApi_HostAddress}}/api/wantlist/
Accept: application/json

DELETE {{MtgTrader.WebApi_HostAddress}}/api/wantlist?wantlistId={wantlistId}
Accept: application/json


###
